server:
  port: 1200
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:  # 路由
        - id: websocket-route
          uri: lb://websocket-server
          predicates:
            - Path=/websocket/**